### ISSUE TITLE
having an error installing "gmp" and "gnuPG" packages

### ISSUE THREAD

**Issue by AkylaiSh** [learn-co-curriculum/phase-0-macos-env-ruby#1]
% brew install gmp
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gmp".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by AkylaiSh** [comment]
https://github.com/Homebrew/discussions/discussions/501#discussioncomment-353822 solved it

**Comment by lizbur10** [comment]
Glad you got it working! I'm going to go ahead and close this issue. 💙
