### ISSUE TITLE
Issue installing Ruby 2.6.1 MacOS

### ISSUE THREAD

**Issue by mnopprapun** [learn-co-curriculum/phase-0-macos-env-ruby#2]
In my terminal I am running into an Error on the install. 

Error running '__rvm_make -j16',
please read /Users/mathawudnopprapun/.rvm/log/1615336176_ruby-2.6.1/make.log

There has been an error while running make. Halting the installation.

If I put in 'rvm list' I get, No rvm rubies installed yet. try 'rvm help install'

**Comment by lizbur10** [comment]
Hi @mnopprapun! We have been seeing this error quite a bit. You should be able to fix it by following the steps for Solution #2 in [this article](https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d). Note that the article specifies Catalina, but it will also work for Big Sur.

I'm going to close this issue so, if the suggestion above does not clear up the problem, or if you run into any other issues, please post in Flatiron's #js-prework-support Slack channel to get additional help.

Cheers 💙
