### ISSUE TITLE
cannot install rvm 2.6.1

### ISSUE THREAD

**Issue by SamJoma** [learn-co-curriculum/phase-0-macos-env-ruby#3]
Error message: Error running '__rvm_make -j8',
please read /Users/samjomaiv/.rvm/log/1616194862_ruby-2.6.1/make.log

There has been an error while running make. Halting the installation.

I tried to google but nothing helps.

**Comment by lizbur10** [comment]
Hi @surick91! If you post a question on the #js-prework-support Slack channel, someone will help you with this 😄 There are instructors available until 9pm ET.
