### ISSUE TITLE
Issue installing GMP and GnuPG packages

### ISSUE THREAD

**Issue by pierce-evans** [learn-co-curriculum/phase-0-macos-env-ruby#9]
### Canvas Link

https://learning.flatironschool.com/courses/6324/pages/installing-ruby-on-macos?module_item_id=496721

### Concern

Error recognizing 'brew' command in terminal.

### Additional Context

<img width="568" alt="Screen Shot 2022-11-11 at 10 52 20 AM" src="https://user-images.githubusercontent.com/118009000/201390557-aca265ef-8e08-435a-aa21-731c81ee5a84.png">

**Comment by jlboba** [comment]
Hello, thank you for opening this issue!

This error implies Homebrew was not installed onto your computer successfully 
before these installations. If the "MacOS System Setup" lesson preceding this one 
is done beforehand, this typically should not be an issue. 

Regardless, I have added a line to address this error message should it occur again 
for students in the future. 

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
